Adds dev observability section
digitalocean/k8s-adoption-journey pull request #24
Opened 2022-09-28 09:43 UTC by v-bpastiu

- adds dev observability section
- metrics server, kubernetes dashboard to be used for development environment observability

2022-09-28 14:21 UTC, v-ctiutiu requested changes

2022-09-28 14:21 UTC, v-ctiutiu commented on docs/02-development/development-observability.md
> +??? note "Click to expand `node desribe command` output"
Typo: `desribe` -> `describe`

2022-09-29 05:36 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +In this section you will install the community maintained [Kubernetes Dashboard](https://github.com/kubernetes/dashboard). Please follow below steps to install it using kubectl:
Fixed in latest commit.

2022-09-29 05:36 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +??? note "Click to expand `node desribe command` output"
Fixed in latest commit.

2022-09-29 07:02 UTC, v-ctiutiu requested changes

2022-09-29 07:04 UTC, v-ctiutiu commented on mkdocs.yml
> +      - Development observability: 02-development/development-observability.md
I would leave only `Observability` as the main title for this section.

2022-09-29 07:07 UTC, v-ctiutiu commented on docs/02-development/setup-ingress.md
> +!!! note
This note should be moved to the Observability section no ?

And I would rephrase like this:

>You will not install a full blown monitoring and logging stack on the development cluster such as Prometheus and Loki, but will do so for the `staging` and `production` clusters.

2022-09-29 07:13 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +    ```
done

2022-09-29 07:15 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +See details about the resources that have been allocated to your nodes, rather than the current resource usage, the kubectl describe command provides a detailed breakdown of a specified pod or node.
Done

2022-09-29 07:17 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +3. Open a web browser and point to the [Kubernetes Dashboard Login](http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:https/proxy/#/login) and add your
Done

2022-09-29 07:17 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +            You will authenticate using the cluster's `kubeconfig` file. To get the config file navigate to your DigitalOcean cloud console, go to `Kubernetes`, select your cluster and from the `Conf
Done

2022-09-29 07:17 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +    You should see the following:
Done

2022-09-29 07:19 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +Once you deploy and log in to Kubernetes Dashboard, you’ll have access to metric summaries for each pod, node, and namespace in your cluster. You can also use the UI to edit Kubernetes objects—for in
Done

2022-09-29 07:19 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +You can also view the stream of logs from a pod in `Kubernetes Dashboard`. From the navigation bar at the top of the `Pods` view, click on the `Logs` tab to access a log stream from the pod in the br
Done

2022-09-29 07:20 UTC, v-bpastiu commented on docs/02-development/development-observability.md
> +Next, you will setup the `staging` environment.
Done

2022-09-29 07:21 UTC, v-bpastiu commented on docs/02-development/setup-ingress.md
> +Next, you will deploy the [Kubernetes Dashboard](https://github.com/kubernetes/dashboard) and [Kubernetes Metrics Server](https://github.com/kubernetes-sigs/metrics-server) which will allow you to vi
Done

2022-09-29 07:21 UTC, v-bpastiu commented on mkdocs.yml
> +      - Development observability: 02-development/development-observability.md
Done

2022-09-29 07:31 UTC, v-bpastiu commented on docs/02-development/setup-ingress.md
> +!!! note
Done

2022-09-29 07:38 UTC, v-ctiutiu approved these changes
Looks good to me.

2022-09-29 07:39 UTC, merged