First commit on the staging section
digitalocean/k8s-adoption-journey pull request #25
Opened 2022-09-30 12:53 UTC by v-bpastiu

- in progress first commit for the staging section

2022-10-03 11:03 UTC, v-ctiutiu requested changes

2022-10-03 11:03 UTC, v-ctiutiu commented on docs/03-staging/deploying-the-app.md
> +
I would add a note in the prerequisites section (or where appropriate), stating that we're using the kubectl built-in version of kustomize.

2022-10-03 11:03 UTC, v-ctiutiu commented on docs/03-staging/setup-ingress.md
> +2. A container registry already set up as explained in the [Set up DOCR](setup-docr.md) section.
Do we need this requirement in the ingress section ?

2022-10-03 11:03 UTC, v-ctiutiu commented on docs/03-staging/observability.md
> +2. A container registry already set up as explained in the [Set up DOCR](setup-docr.md) section.
Do we need this requirement in the ingress section ?

2022-10-03 11:05 UTC, v-ctiutiu commented on docs/03-staging/setup-doks.md
> +1. A container registry already set up as explained in the [Set up DOCR](setup-docr.md) section.
Do we need this requirement in the doks section ?

2022-10-03 11:16 UTC, v-bpastiu commented on docs/03-staging/deploying-the-app.md
> +
Done

2022-10-03 11:50 UTC, v-bpastiu commented on docs/03-staging/deploying-the-app.md
> +    kubectl apply -k kustomize/staging
Done.

2022-10-03 12:08 UTC, v-ctiutiu requested changes

2022-10-03 12:08 UTC, v-ctiutiu commented on docs/01-getting-started/setup-docr.md
> +        You will be pushing an initial release first to DOCR (1.0.0) and use that to deploy to the `staging` and `production` environments in the upcoming sections. Then, ArgoCD will take care of the
ArgoCD doesn't build and push images. It is responsible with GitOps part. It means, it will sync your DOKS cluster with the K8S manifests present in the linked GitHub repository.

The CI part, meaning GitHub actions takes care of that.

2022-10-03 12:09 UTC, v-bpastiu commented on docs/01-getting-started/setup-docr.md
> +        You will be pushing an initial release first to DOCR (1.0.0) and use that to deploy to the `staging` and `production` environments in the upcoming sections. Then, ArgoCD will take care of the
My bad. Fixing now.

2022-10-03 14:02 UTC, v-ctiutiu requested changes

2022-10-03 14:02 UTC, v-ctiutiu commented on docs/03-staging/observability.md
> +4. The online boutique sample application deployed to your cluster as explained in the [Deploying the app](deploying-the-app.md) section.
Make sure to change link title here as well, if going with my suggestion about renaming.

2022-10-03 14:04 UTC, v-bpastiu commented on docs/03-staging/setup-doks.md
> +1. Doctl utility already installed as explained in the [Installing Required Tools -> Doctl](installing-required-tools.md#installing-doctl) section.
Fixed in latest commit.

2022-10-03 14:05 UTC, v-bpastiu commented on docs/03-staging/setup-doks.md
> +Following command will create a DigitalOcean Kubernetes cluster named `microservices-demo-staging`, with a pool size of `3 nodes`, auto-scale to `2-4` each having `4 vCPUs` and `8gbGB` of RAM, in the
Will make sure and test this tomorrow.

2022-10-03 14:07 UTC, v-bpastiu commented on mkdocs.yml
> +      - Deploying the application: 03-staging/deploying-the-app.md
Changed.

2022-10-04 11:12 UTC, v-ctiutiu approved these changes
Looks good to me now.

2022-10-04 11:12 UTC, merged