Adds production environment
digitalocean/k8s-adoption-journey pull request #27
Opened 2022-10-07 12:13 UTC by v-bpastiu

- adds production environment, docs and assets
- fixes syntax highlighting for collapsible blocks

2022-10-07 12:36 UTC, v-ctiutiu requested changes
Also, a very important thing to remember - although we decided to create a dedicated chapter per environment, we should also think about tuning various values per each stack.

For example, in case of DOKS, you already did that by telling the user to use specific configuration per env (such as number of nodes, node size, etc).

We should tune other stacks as well, such as Prometheus, Loki, Ingress, Cert-Manager, etc. For example in case of Prometheus and Loki we need to make sure to use enough PVC size to store more metrics, rather than using the default value of 5G (which is small for PROD envs, I would say).

Also metrics and logs retention duration plays a key role as well. Applies to both Prometheus and Loki.

We use S3 storage for Loki - does it scale well in a production env also ? When dealing with multiple logs data, is query speed affected ?

Other things to look for is number of replicas for each stack - make sure that a minimum of 2 is present all the time.

I think there other aspects to look at, but this is what comes in my mind now. 

Thanks.

2022-10-07 12:36 UTC, v-ctiutiu commented on docs/04-production/deploying-the-online-boutique-sample-application-production.md
> +        You will be using the `kubectl` built-in verion of [Kustomize](https://kustomize.io/).
Typo: verion -> version.

2022-10-08 22:47 UTC, udhay45 approved these changes

2022-10-10 09:37 UTC, v-ctiutiu approved these changes
Looks good to me now.

2022-10-10 09:38 UTC, merged